SELECT
    TO_CHAR(TRUNC(ACTION_DATE), 'YYYY-MM-DD') AS "day",
    COUNT(PROV_SERVICE_NAME) AS "value"
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY TRUNC(ACTION_DATE)
ORDER BY 1