SELECT
    TO_CHAR(TRUNC(ACTION_DATE, 'MM'), 'YYYY-MM-DD') AS month,
    SUM(
        CASE
            WHEN (TOTAL_CHARGE_30_DAYS_AFT - TOTAL_CHARGE_30_DAYS_BFR) > 0
            THEN 1 ELSE 0
        END
    ) AS up,
    SUM(
        CASE
            WHEN (TOTAL_CHARGE_30_DAYS_AFT - TOTAL_CHARGE_30_DAYS_BFR) <= 0
            THEN 1 ELSE 0
        END
    ) AS down
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY TRUNC(ACTION_DATE, 'MM')
ORDER BY 1