SELECT
    TO_CHAR(TRUNC(ACTION_DATE, 'MM'), 'YYYY-MM-DD') AS date,
    COUNT(PROV_SERVICE_NAME) AS sales
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY TRUNC(ACTION_DATE, 'MM')
ORDER BY TRUNC(ACTION_DATE, 'MM')