SELECT
    TO_CHAR(TRUNC(ACTION_DATE), 'YYYY-MM-DD') AS "day",
    SUBSTR(PREVIOUS_SERVICE_NAME, 4, LENGTH(PREVIOUS_SERVICE_NAME)) AS "old_name",
    SUBSTR(PROV_SERVICE_NAME, 4, LENGTH(PROV_SERVICE_NAME)) AS "new_name",
    COUNT(*) AS "value"
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) = TO_DATE(:report_date,   'YYYY-MM-DD')
GROUP BY TRUNC(ACTION_DATE), PREVIOUS_SERVICE_NAME, PROV_SERVICE_NAME
ORDER BY "value" DESC