SELECT
    TO_CHAR(TRUNC(ACTION_DATE), 'YYYY-MM-DD') AS "day",
    (CPC.LASTNAME || ' ' || CPC.FISTNAME)     AS "name",
    ROUND(
        SUM(CASE WHEN MIN_RENEWAL_DATE IS NOT NULL THEN 1 ELSE 0 END)
        / COUNT(PROV_SERVICE_NAME) * 100
    ) AS "value"
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW CORDGM
LEFT JOIN CRM_PLATFORM.CRMUSER CPC
       ON CPC.ID = CORDGM.USER_ID
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY TO_CHAR(TRUNC(ACTION_DATE), 'YYYY-MM-DD'),
         (CPC.LASTNAME || ' ' || CPC.FISTNAME)
ORDER BY 1