SELECT
    TO_CHAR(TRUNC(ACTION_DATE), 'YYYY-MM-DD') AS "day",
    CPC.LASTNAME || ' ' || CPC.FISTNAME AS "user_name",
    COUNT(USER_ID) AS "value"
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW CORDGM
LEFT JOIN CRM_PLATFORM.CRMUSER CPC
       ON CPC.ID = CORDGM.USER_ID
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY
    CPC.LASTNAME || ' ' || CPC.FISTNAME,
    TRUNC(ACTION_DATE)
ORDER BY 1