SELECT
    TO_CHAR(TRUNC(ACTION_DATE), 'YYYY-MM-DD') AS "day",
    SUM(
        CASE
            WHEN TRUNC(ACTION_DATE) = COALESCE(TRUNC(AT_PAY_1_DATE), TRUNC(ACTION_DATE) + 1)
            THEN RENEWAL_QNT ELSE 0
        END
    ) AS "active",
    SUM(
        CASE
            WHEN TRUNC(ACTION_DATE) < COALESCE(TRUNC(AT_PAY_1_DATE), TRUNC(ACTION_DATE) + 1)
            THEN RENEWAL_QNT ELSE 0
        END
    ) AS "suspended"
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY TRUNC(ACTION_DATE)
ORDER BY 1