SELECT
    to_char(trunc(ACTION_DATE), 'YYYY-MM-DD') AS "day",
    SUBSTR(PROV_SERVICE_NAME, 4, LENGTH(PROV_SERVICE_NAME)) AS "name",
    SUM(
        CASE
            WHEN USED_IN_REPORT IS NULL
                THEN PROV_SERVICE_PRICE + (PROV_SERVICE_PRICE * RENEWAL_QNT)
            ELSE NULL
        END
    ) AS "value"
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY trunc(ACTION_DATE), PROV_SERVICE_NAME
ORDER BY 1