SELECT
    TO_CHAR(TRUNC(ACTION_DATE, 'MM'), 'YYYY-MM-DD') AS day,
    SUM(
        CASE
            WHEN USED_IN_REPORT IS NULL
            THEN PROV_SERVICE_PRICE + (PROV_SERVICE_PRICE * RENEWAL_QNT)
            ELSE NULL
        END
    ) AS value
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY TRUNC(ACTION_DATE, 'MM')
ORDER BY 1