SELECT
    TO_CHAR(TRUNC(ACTION_DATE), 'YYYY-MM-DD') AS "day",
    SUBSTR(PROV_SERVICE_NAME, 4, LENGTH(PROV_SERVICE_NAME)) AS "name",
    ROUND(
        SUM(CASE WHEN MIN_RENEWAL_DATE IS NOT NULL THEN 1 ELSE 0 END)
        / COUNT(PROV_SERVICE_NAME) * 100
    ) AS "value"
FROM KPI.COM_ORW_REWARD_DETAILED_GTM_MW
WHERE TRUNC(ACTION_DATE) >= TO_DATE(:start_date, 'YYYY-MM-DD')
  AND TRUNC(ACTION_DATE) <  TO_DATE(:end_date,   'YYYY-MM-DD')
GROUP BY TRUNC(ACTION_DATE), PROV_SERVICE_NAME
ORDER BY 1
